config/routes.rb
require 'sidekiq/web'
TopicHog::Application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'

  authenticated :user do
    root :to => 'static_pages#home'
  end
  
  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help'
  match '/learn_more', to: 'static_pages#learn_more'
  match '/privacy_statement', to: 'static_pages#privacy_statement'
  match '/terms_of_use', to: 'static_pages#terms_of_use'  
  match '/how-to-create-a-profession-portfolio', to: 'static_pages#professional_landing_page'
  
  resources :posts, only: [:index, :destroy]
  resources :messages, only: [:new, :create]
  get 'posts/:tag1', to: 'posts#index', as: :post

  
  devise_for :users, controllers: {omniauth_callbacks: "authentications", registrations: "registrations" } 
  
  resources :authentications
  resources :token_authentications, :only => [:create, :destroy]
  resources :topicdraftimages, :only => [:create, :update, :edit, :destroy]
  resources :projectdraftimages, :only => [:create, :update, :edit, :destroy]
  resources :users, :only => [:show, :index] do
    member do
      get :following, :followers 
    end
    member do
      get :liked
    end
    resources :posts, only: [:index] do
      member do
        get :likers
      end
    end

    resources :projects, :only => [:show] do
      member do
        put :publicise
      end  
    end 
    resources :projectdrafts, :only => [:create, :show, :new, :edit, :destroy] do
     member do
        get :publish
      end
     member do
        get :discard
      end       
    end
    resources :projectdrafts, :only => [ :update] , as: :update_projectdrafts
    resources :pposts, :only => [:create, :show, :new] 
    resources :tposts, :only => [:create, :show, :new] 
    resources :topics, :only => [:create, :show, :new, :edit] do
      member do
        put :publicise
      end  
    end    
    resources :topics, :only => [ :update] , as: :update_topics
    resources :topicdrafts, :only => [:create, :show, :new, :edit, :destroy] do
     member do
        get :publish
      end
     member do
        get :discard
      end 
    end
    resources :topicdrafts, :only => [ :update] , as: :update_topicdrafts
  end

  
  resources :profiles, only: [:edit, :update, :show]
  resources :user_preferences, only: [:edit, :update]
  resources :avatars, only: [:edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :tags_names
  
  mount Sidekiq::Web, at: '/sidekiq'

  if Rails.env.development?
    app = ActionDispatch::Static.new(
      lambda{ |env| [404, { 'X-Cascade' => 'pass'}, []] },
      Rails.application.config.paths['public'].first,
      Rails.application.config.static_cache_control
    )

    mount app, :at => '/', :as => :public
  end
end

app/controllers/static_pages_controller.rb
require 'will_paginate/array' 

class StaticPagesController < ApplicationController
  def home
    tag_cloud

    if user_signed_in?
      @project_feed_items = current_user.project_feed.page(params[:project_page]).per_page(5)
      @topic_feed_items = current_user.topic_feed.page(params[:topic_page]).per_page(5)
      @feed_items = current_user.feed.page(params[:feed_page]).per_page(5)
      @liked_posts = current_user.liked_posts.page(params[:liked_page]).per_page(5)       
    end
  end

  def help
  end
  
   def learn_more
  end
  
  def professional_landing_page
    @hide_navbar = true
  end
  
  def tag_cloud
    @tags = Post.tag_counts_on(:tags)
    @tags.sort! { |a,b| b.count <=> a.count }
    @tags = @tags[0..40]

  end 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/static_pages/_features.html.haml
%section#features 
  .well.well-small
    %h3 What is it?
  .row  
    .span3
      %h5.center Create your profile
      =image_tag("profile.png")  
      %p
        Your profile includes a short bio where you describe who you are and what you are about. 
      %p  
        You can include links to you twitter, facebook, linkedin, blog and website.
      %p 
      Check out an existing
      = link_to "profile", user_path(1)
      \.
    .span3
      %h5.center Build your knowledge portfolio
      =image_tag("projects&topics.png")
      %p 
        You are knowledgeable about many things and have built up experience while
        working and studying. 
      %p  
        Build your knowledge portfolio by documenting
        %strong Topics
        and
        %strong Projects.
    .span3
      %h5.center Share anywhere
      =image_tag("topichog-to-facebook-twitter-linkedin.png")
      %p  
        Add a link to your profile on linkedin, Twitter or email a link. 
      %p  
        Your 
        %strong topics
        and
        %strong projects 
        will be seen by viewers of your profile.          
  .row.spacer50 
    %br.bs-docs-separator    
  .row  
    .span3
      .spacer20
      %p
        Topics and Projects are blog posts 
        that document a piece of knowledge that you have or a project that
        you have done. 
      %p
        = link_to "Explore", posts_path   
        projects and topics created by others.
    .span3
      %h5.center Topics
      %a{"data-toggle" => "modal", :href => "#topicModal", :role => "button", "data-show" => false}                    
        =image_tag("topic.png")  
        Click here to view
    .span3
      %h5.center Projects
      %a{"data-toggle" => "modal", :href => "#projectModal", :role => "button", "data-show" => false}          
        =image_tag("project.png")
        Click here to view
  .spacer50      

app/views/static_pages/_jobseekers.html.haml
%h3 Professionals and Jobseekers
.spacer20
.row
  .span9
    .row
      .span3
        =image_tag("portfolio.png", class: 'img-150')       
      .span6
        %h5
          Create your professional portfolio    
        %p Your TopicHog profile showcases your knowledge and project work. It's your professional portfolio. 
        %ul
          %li Link from your Linkedin profile (links can be added in the contact info section of your Linkedin profile). 
          %li Add a link to your TopicHog profile on your CV.

app/views/static_pages/_landing_sign_up.html.haml
.row
  .span3
    = form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f|
      = devise_error_messages!
      %div
        = f.label :name        
        = f.text_field :name        
      %div
        %br/
        = f.label :email, "Email"        
        = f.email_field :email
      %div
        %br/
        = f.label :password        
        = f.password_field :password
      %div
        %br/
        = f.label :password_confirmation        
        = f.password_field :password_confirmation
      .spacer10
      %div= f.submit "Create your portfolio", class: "btn btn-large btn-primary"

app/views/static_pages/_students.html.haml
%h3 Students
.spacer20
.row
  .span9
    .row
      .span6
        %h5
          Write up your notes     
        %p Know a topic in depth? 
        %p Create a topic and add your notes and link to useful resources (papers, sites etc).
      .span3
        =image_tag("study-notes2.png", class: 'img-150')   
    .spacer20
    .row
      .span3
        =image_tag("project-icon.png", class: 'img-100')        
      .span6
        %h5
          Show off your projects 
        %p Finished some projects recently?
        %p
          Post up the executive summaries of your projects and attach the project report.   
    .spacer20          
    .row
      .span6
        %h5
          Share with your class and your network
        %p Share your topics and projects on twitter, linkedin, or your class facebook group.
        %p At exam time benefit from what others have shared.   
      .span3
        =image_tag("topichog-to-facebook-twitter-linkedin.png", class: 'img-150')     
           

app/views/static_pages/help.html.haml
= provide(:title, 'Help')
%h1 Help page
%p
  This is the TopicHog Help page

app/views/static_pages/home.html.haml
- if user_signed_in?
  .row
    %aside.span4
      %section
        = render 'shared/user_info'
      %section
        = render 'shared/stats'
    .span8
      - if @feed_items.any?
        %h3.well.well-small Feed
        = render partial: 'shared/feed'
      - if @liked_posts.any?
        %h3.well.well-small Favorited items (#{@liked_posts.count})
        = render partial: 'shared/liked_feed'        
      - if @project_feed_items.any?
        %h3.well.well-small Project Feed
        = render partial: 'shared/project_feed'
      - if @topic_feed_items.any?
        %h3.well.well-small Topic Feed
        = render partial: 'shared/topic_feed'
      %h3.well.well-small 
        =link_to 'Explore topics and projects', posts_path
      #popular_tags.span8 
        -tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class|
          = link_to tag.name, post_path(tag.name), :class => 'label', method: :GET      
      .spacer200      
- else
  .row.center.hero-unit
    %h1 TopicHog
    %h2
      Your knowledge and project portfolio 
    .spacer50  
    %Span
      Sign in the easy way
    \#{link_to image_tag("twitter_64.png", class: 'signin_icon'), user_omniauth_authorize_path(:twitter)} 
    \#{link_to image_tag("facebook_64.png", class: 'signin_icon'), user_omniauth_authorize_path(:facebook)}  
    \#{link_to image_tag("linkedin_64.png", class: 'signin_icon'), user_omniauth_authorize_path(:linkedin)} 
    %Span
      or 
    \#{link_to "Sign up here", new_user_registration_path}            
  .row
    .span4
      %h2.center Create your profile 
    .span4
      %h2.center
        Showcase your 
        %br knowledge and work     
    .span4
      %h2.center 
        Share your 
        %br profile and content      
  .row.home-img 
    .span4
      =image_tag("profile.png")  
      %p
        Describe who you are and what you are about,
        include links to you twitter, facebook, linkedin, blog and website.
      %p 
      Checkout an existing
      = link_to "profile", user_path(1)
    .span4
      =image_tag("projects&topics.png") 
      %p  
        Build your knowledge portfolio by documenting
        %strong Topics
        and
        %strong Projects.
      %p
        = link_to "Explore", posts_path   
        projects and topics created by others        
    .span4
      =image_tag("topichog-to-facebook-twitter-linkedin.png")
      %p  
        Add a link to your profile on linkedin or on your CV. 
      %p  
        Share your 
        %strong topics
        and
        %strong projects 
        on twitter, facebook or linkedin.              

app/views/static_pages/learn_more.html.haml
= provide(:title, 'Learn more')
.row
  #nav-left-div.span3.divheight5
    %ul#nav-left.span2.nav.nav-list.nav-stacked.affix-top{"data-offset-top" => "10", "data-spy" => "affix"}
      %li#features-tab.nav-header
        %a{:href => '#features' }
          %h4.muted
            What is it?
            %i.icon-chevron-right.bs-docs-sidenav      
      %li#cases-tab.nav-header
        %a{:href => '#cases' }
          %h4.muted
            How can I use it?
            %i.icon-chevron-right.bs-docs-sidenav     
      %li#student-case-tab
        %a{:href => '#student-case' }
          %h6.muted
            Students
      %li#professional-case-tab.hide
        %a{:href => '#professional-case' }
          %h6.muted
            Professionals
      %li#jobseeker-case-tab
        %a{:href => '#jobseeker-case' }
          %h6.muted
            Professionals and Jobseekers
      %li#company-case-tab.hide
        %a{:href => '#company-case' }
          %h6.muted
            companies  
      %li#institution-case-tab.hide
        %a{:href => '#institution-case' }
          %h6.muted
            Institutions                                                      
      %li#pricing-tab.nav-header
        %a{:href => '#pricing' }
          %h4.muted
            Pricing
            %i.icon-chevron-right.bs-docs-sidenav
      %li#about-tab.nav-header
        %a{:href => '#about' }
          %h4.muted
            About us
            %i.icon-chevron-right.bs-docs-sidenav
      %li
        .spacer20  
        .span2
          = link_to "Sign up now!", new_user_registration_path, class: "btn btn-small btn-primary"                                          
    .span1
  .span9
    =render partial: 'features'                  
    .spacer100
    %section#cases
      .well.well-small
        %h3 How can I use it?
      %section#student-case 
        =render partial: 'students'
      %section#professional-case.hide 
        %h3 Professionals
      %section#jobseeker-case 
        =render partial: 'jobseekers'
      %section#company-case.hide 
        %h3 Companies
      %section#institution-case.hide 
        %h3 Institutions           
    .spacer100
    %section#pricing 
      .well.well-small 
        %h3 Pricing
    %h4 It's Free!
    %P
      We are in Beta and may offer premium features in the future.         
    .spacer100
    %section#about 
      .well.well-small 
        %h3 About us
      %h4 We are a web start-up based in Dublin 
      %p You can contact us email at support@topichog.com
    .spacer200       
    .spacer200 
    .spacer200  
#topicModal.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#topicModalLabel Example topic
  .modal-body
    %p
      =image_tag("topic_2_full.png")
  .modal-footer
    %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Close
    =link_to 'View Topic', user_topic_path(1,2), class: "btn btn-primary"     
#projectModal.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#projectModalLabel Example project
  .modal-body
    %p
      =image_tag("project_2_full.png")
  .modal-footer
    %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Close
    =link_to 'View Project', user_project_path(1,3), class: "btn btn-primary"     

app/views/static_pages/privacy_statement.html.haml
= provide(:title, 'Privacy statement')
%h3 Privacy Statement
.spacer50
= render :partial => 'layouts/privacy_statement' 

app/views/static_pages/professional_landing_page.html.haml
= provide(:title, 'how-to-create-a-profession-portfolio')
.row
  .span12 
    %h3.center  How to create your (free) professional portfolio
.spacer10
.row
  .span12
    %h2  
      Showcase examples of great work you have done.
.spacer30   
.row
  .span8
    .row 
      .span6.hero-unit 
        .row
          %p 
            %strong 1. Create your account on TopicHog   
        .row    
          .span6 Sign up for free. There are no ads and no catches. We won't do any unpleasent things with your contact details. 
        .spacer10        
        .row  
          %p 
            %strong 2. Create a profile bio
        .row
          .span6 Your profile bio is a short summary of who you are professionally. You can link to your other presences online, such as linkedin if you want people to see a more detailed profile.
        .spacer10
        .row
          %p 
            %strong 3. Add your projects
        .row   
          .span3
            Write a detailed and attractive account of your projects.
          .span2
            %a{"data-toggle" => "modal", :href => "#projectModal", :role => "button", "data-show" => false}          
              =image_tag("project.png", size: "150x150")
              .span2 Click to view                     
        .row
          %p
            %strong 4. Create topics that display your knowledge  
        .row  
          .span3
            Write about topics that you are knowledgable about.
          .span2
            %a{"data-toggle" => "modal", :href => "#topicModal", :role => "button", "data-show" => false}                    
              =image_tag("topic.png", size: "150x150")  
              .span2 Click to view    
        .spacer10
        .row
          %p
            %strong 5. Share your portfolio with your network  
          .span3  
            Share your profile with your network on linkedin, Twitter and elsewhere. 
            .spacer5
            %div  
              Your 
              %strong topics
              and
              %strong projects 
              will be seen by viewers of your profile. 
          .span2
            %h5.center
            =image_tag("topichog-to-facebook-twitter-linkedin.png")       
  .span4
    .row
      .span3
        %h2 Create your portfolio now!
        = render partial: 'landing_sign_up'
    .spacer30 
    .row     
      .span3 
        .muted Why have a professional portfolio?   
        .spacer10
        %div
          Rather than only hearing about your success, a professional portfolio 
          actually showcases examples your best work. 
        .spacer10  
        %div Make a good first impression and show that you are a serious and knowledable professional.                                                   
#topicModal.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#topicModalLabel Example topic
  .modal-body
    %p
      =image_tag("topic_2_full.png")
  .modal-footer
    %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Close
    =link_to 'View Topic', user_topic_path(1,2), class: "btn btn-primary"     
#projectModal.modal.hide.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-header
    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
    %h3#projectModalLabel Example project
  .modal-body
    %p
      =image_tag("project_2_full.png")
  .modal-footer
    %button.btn{"aria-hidden" => "true", "data-dismiss" => "modal"} Close
    =link_to 'View Project', user_project_path(1,3), class: "btn btn-primary"          

app/views/static_pages/terms_of_use.html.haml
= provide(:title, 'Terms of use')
= render :partial => 'layouts/terms_of_use' 