config/routes.rb
require 'sidekiq/web'
TopicHog::Application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'

  authenticated :user do
    root :to => 'static_pages#home'
  end
  
  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help'
  match '/learn_more', to: 'static_pages#learn_more'
  match '/privacy_statement', to: 'static_pages#privacy_statement'
  match '/terms_of_use', to: 'static_pages#terms_of_use'  
  match '/how-to-create-a-profession-portfolio', to: 'static_pages#professional_landing_page'
  
  resources :posts, only: [:index, :destroy]
  resources :messages, only: [:new, :create]
  get 'posts/:tag1', to: 'posts#index', as: :post

  
  devise_for :users, controllers: {omniauth_callbacks: "authentications", registrations: "registrations" } 
  
  resources :authentications
  resources :token_authentications, :only => [:create, :destroy]
  resources :topicdraftimages, :only => [:create, :update, :edit, :destroy]
  resources :projectdraftimages, :only => [:create, :update, :edit, :destroy]
  resources :users, :only => [:show, :index] do
    member do
      get :following, :followers 
    end
    member do
      get :liked
    end
    resources :posts, only: [:index] do
      member do
        get :likers
      end
    end

    resources :projects, :only => [:show] do
      member do
        put :publicise
      end  
    end 
    resources :projectdrafts, :only => [:create, :show, :new, :edit, :destroy] do
     member do
        get :publish
      end
     member do
        get :discard
      end       
    end
    resources :projectdrafts, :only => [ :update] , as: :update_projectdrafts
    resources :pposts, :only => [:create, :show, :new] 
    resources :tposts, :only => [:create, :show, :new] 
    resources :topics, :only => [:create, :show, :new, :edit] do
      member do
        put :publicise
      end  
    end    
    resources :topics, :only => [ :update] , as: :update_topics
    resources :topicdrafts, :only => [:create, :show, :new, :edit, :destroy] do
     member do
        get :publish
      end
     member do
        get :discard
      end 
    end
    resources :topicdrafts, :only => [ :update] , as: :update_topicdrafts
  end

  
  resources :profiles, only: [:edit, :update, :show]
  resources :user_preferences, only: [:edit, :update]
  resources :avatars, only: [:edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :tags_names
  
  mount Sidekiq::Web, at: '/sidekiq'

  if Rails.env.development?
    app = ActionDispatch::Static.new(
      lambda{ |env| [404, { 'X-Cascade' => 'pass'}, []] },
      Rails.application.config.paths['public'].first,
      Rails.application.config.static_cache_control
    )

    mount app, :at => '/', :as => :public
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :summary, :title, :tag_list, :content, :reference, :image
  
  has_many :posts, as: :postable, :dependent => :destroy
  has_one :topicdraft, dependent: :destroy
  has_many :topicdraftimages, dependent: :destroy
  
  acts_as_taggable_on :tags
  
  mount_uploader :image, TopicdraftimageUploader
  
  default_scope order: 'topics.created_at DESC'  

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  def show  
    @topic_user = User.find_by_id(params[:user_id]) 
    @post = @topic_user.posts.topic_with_postable_id(params[:id])
    @topic = @post.postable   
    @user = @post.user
    @likers = @post.likers#.paginate(page: params[:page])
    @likes_count =  @post.likes_count
    @tags_item = @post.owner_tags_on(@user, :tags)
    @topicdraftimage = Topicdraftimage.topicdraftimage_for_topic(@topic).first
    @twitter_auth = @user.authentications.find_by_provider('twitter')
    @facebook_auth = @user.authentications.find_by_provider('facebook')
    @linkedin_auth = @user.authentications.find_by_provider('linkedin') 
    @tag0 = @topic.tag_list[0]
    @tag1 = @topic.tag_list[1]    
  end
  
  def publicise
      @topic = Topic.find_by_id(params[:id])
      @user = @topic.posts[0].user
      linkedin_publicise = params[:linkedin_pub] == '1' ? true : false 
      facebook_publicise = params[:facebook_pub] == '1' ? true : false 
      twitter_publicise = params[:twitter_pub] == '1' ? true : false 
    if @topic.topicdraftimages.count > 0
      has_image = true
    elsif @topic.topicdraftimages.count == 0
      has_image = false
    end     
     if !linkedin_publicise && !facebook_publicise && !twitter_publicise
      flash[:failure] = "You need to select the networks that you want to post to!"
     else
       PublishWorker.perform_async(current_user.id, user_topic_url(@user, @topic), @topic.id, "Topic", linkedin_publicise, facebook_publicise, twitter_publicise, has_image) 
       flash[:success] = "Topic posted to your networks!"
     end  
     redirect_to user_topic_path(@user, @topic)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_url_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
  
  def topicdraftimage_for(topic)
    
    user = topic.posts.first.user

    twitter_auth = user.authentications.find_by_provider('twitter')
    facebook_auth = user.authentications.find_by_provider('facebook')
    linkedin_auth = user.authentications.find_by_provider('linkedin')   
    
    if user.avatar.image?
      user.avatar.image_url(:thumb).to_s
    elsif linkedin_auth
      user.linkedin_avatar   
    elsif twitter_auth
      user.twitter_avatar    
    elsif facebook_auth
      user.fb_avatar    
    else
      gravatar_url_for user, size: 52
    end  
  end
end

app/views/topics/_edit_topic_form.html.haml
= form_for(@topic, :url => user_update_topic_path(@user, @post), :html => { :method => "put" }) do |f|
  = render partial: 'shared/error_messages', locals: {object: f.object}
  .field
    %h2.span8 Edit Topic
    %p.span8
      .span1
        = f.label :title, "Title"
      .span6  
        = f.text_field :title, placeholder: "Topic title..."
    %p.span8
      .span1
        = f.label :summary, "Summary"
      .span6          
        = f.text_area :summary, placeholder: "Topic summary...", rows: 3
    %p.span8
      .span1
        = f.label :reference, "Links & references"
      .span6   
        = f.text_area :reference, :id =>'reference_textarea', placeholder: "Topic references and links..."                     
    %p.span8
      .span1
        = f.label :tag_list, "Tags"
      .span6       
        = f.text_field :tag_list, placeholder: "Comma separated tags..."      
    %p.span8   
      = f.text_area :content, :id =>'content_textarea', placeholder: "Topic content..."
    %p.span8  
      = f.submit "Submit topic", class: "btn btn-large btn-primary"

app/views/topics/show.html.haml
= provide(:title, @user.name + ' | ' + @topic.title)
- content_for :head do
  = tag :meta, property: "og:type", content: "article"     
  = tag :meta, property: "og:url", content: user_topic_url(@user, @topic)
  = tag :meta, property: "og:site_name", content: "topichog"
  -if !@topicdraftimage.nil?
    = tag :meta, property: "og:image", content: image_path(@topicdraftimage.image_url(:large).to_s)
  -else
    = tag :meta, property: "og:image", content: image_path("https://topichogire.s3.amazonaws.com/assets/logo_180.png")
  = tag :meta, property: "og:title", content: @topic.title
  = tag :meta, property: "og:description", content: @topic.summary
  = tag :meta, property: "article:published_time", content: @topic.created_at
  = tag :meta, property: "article:modified_time", content: @topic.updated_at
  = tag :meta, property: "article:tag", content: @tag0
  = tag :meta, property: "article:tag", content: @tag1
  = tag :meta, name: "twitter:card", content: "summary"  
  = tag :meta, name: "twitter:url", content: user_topic_url(@user, @topic) 
  = tag :meta, name: "twitter:title", content: @topic.title    
  = tag :meta, name: "twitter:description", content: @topic.summary     
  -if !@topicdraftimage.nil?
    = tag :meta, name: "twitter:image", content: image_path(@topicdraftimage.image_url(:large).to_s)    
  -else
    = tag :meta, name: "twitter:image", content: image_path("https://topichogire.s3.amazonaws.com/assets/logo_180.png")
  = tag :meta, name: "twitter:site", content: "@topichog"
.row
  %aside.span4
    %section  
      = render 'shared/user_info' 
    %section
      = render 'shared/stats'   
    = render partial: 'users/follow_form' if user_signed_in? 
    .spacer50
    %section.my-hero-unit
      %h4 Links and references:
      .ref 
        =raw @topic.reference 
    %section.my-hero-unit
      =render 'shared/post_stats'
      =render 'shared/likers_list'   
  .span8  
    .row.my-hero-unit
      .span8
        .row 
          .span1
            -if !@topicdraftimage.nil?
              = image_tag(@topicdraftimage.image_url(:thumb).to_s, alt: "", class: "img-polaroid row")
            -if @topicdraftimage.nil?
              = avatar_for @user, size: 52           
          .span5
            %h3         
              =@topic.title
            %div  
              =@topic.summary 
            %p
              =render 'shared/tags'              
          -if user_signed_in? 
            .span2
              =render 'posts/like_form'         
          -if @user == current_user
            .span2
              .row                              
                .span2
                  =render 'shared/topic_publicise_form'    
                .spacer5 
                .span2               
                  = link_to "edit topic", edit_user_topicdraft_path(@user, @post.postable.topicdraft) 
    .row
      .span8                 
        .row
          .span8
            =raw @topic.content