config/routes.rb
require 'sidekiq/web'
TopicHog::Application.routes.draw do
  
  mount Ckeditor::Engine => '/ckeditor'

  authenticated :user do
    root :to => 'static_pages#home'
  end
  
  root to: 'static_pages#home'
  match '/help', to: 'static_pages#help'
  match '/learn_more', to: 'static_pages#learn_more'
  match '/privacy_statement', to: 'static_pages#privacy_statement'
  match '/terms_of_use', to: 'static_pages#terms_of_use'  
  match '/how-to-create-a-profession-portfolio', to: 'static_pages#professional_landing_page'
  
  resources :posts, only: [:index, :destroy]
  resources :messages, only: [:new, :create]
  get 'posts/:tag1', to: 'posts#index', as: :post

  
  devise_for :users, controllers: {omniauth_callbacks: "authentications", registrations: "registrations" } 
  
  resources :authentications
  resources :token_authentications, :only => [:create, :destroy]
  resources :topicdraftimages, :only => [:create, :update, :edit, :destroy]
  resources :projectdraftimages, :only => [:create, :update, :edit, :destroy]
  resources :users, :only => [:show, :index] do
    member do
      get :following, :followers 
    end
    member do
      get :liked
    end
    resources :posts, only: [:index] do
      member do
        get :likers
      end
    end

    resources :projects, :only => [:show] do
      member do
        put :publicise
      end  
    end 
    resources :projectdrafts, :only => [:create, :show, :new, :edit, :destroy] do
     member do
        get :publish
      end
     member do
        get :discard
      end       
    end
    resources :projectdrafts, :only => [ :update] , as: :update_projectdrafts
    resources :pposts, :only => [:create, :show, :new] 
    resources :tposts, :only => [:create, :show, :new] 
    resources :topics, :only => [:create, :show, :new, :edit] do
      member do
        put :publicise
      end  
    end    
    resources :topics, :only => [ :update] , as: :update_topics
    resources :topicdrafts, :only => [:create, :show, :new, :edit, :destroy] do
     member do
        get :publish
      end
     member do
        get :discard
      end 
    end
    resources :topicdrafts, :only => [ :update] , as: :update_topicdrafts
  end

  
  resources :profiles, only: [:edit, :update, :show]
  resources :user_preferences, only: [:edit, :update]
  resources :avatars, only: [:edit, :update]
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :tags_names
  
  mount Sidekiq::Web, at: '/sidekiq'

  if Rails.env.development?
    app = ActionDispatch::Static.new(
      lambda{ |env| [404, { 'X-Cascade' => 'pass'}, []] },
      Rails.application.config.paths['public'].first,
      Rails.application.config.static_cache_control
    )

    mount app, :at => '/', :as => :public
  end
end

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li
          * #{msg}

app/views/shared/_liked_feed.html.haml
%ol.feed
  = render partial: 'shared/liked_feed_item', collection: @liked_posts
= will_paginate @liked_posts, :param_name => 'liked_page', 
                previous_label: h("<"), next_label: h(">"), 
                inner_window: 2, outer_window: 2

app/views/shared/_liked_feed_item.html.haml
%li.feedpost{:id => liked_feed_item.id}
  -if liked_feed_item.postable_type == "Project"
    -if liked_feed_item.postable.projectdraftimages.count == 0
      = avatar_for liked_feed_item.user, size: 52 
    -else
      = image_tag(liked_feed_item.postable.projectdraftimages.first.image_url(:thumb).to_s, alt: "", class: "img-polaroid")    
  -if liked_feed_item.postable_type == "Topic"
    -if liked_feed_item.postable.topicdraftimages.count == 0
      = avatar_for liked_feed_item.user, size: 52 
    -else
      = image_tag(liked_feed_item.postable.topicdraftimages.first.image_url(:thumb).to_s, alt: "", class: "img-polaroid")    
  %div
    - if liked_feed_item.postable_type == "Ppost"
      = link_to liked_feed_item.postable.title, 
          user_ppost_path(liked_feed_item.user.id, 
          liked_feed_item.postable), id: "ppost_link_#{liked_feed_item.id}"
    - if liked_feed_item.postable_type == "Tpost"   
      = link_to liked_feed_item.postable.title, 
        user_tpost_path(liked_feed_item.user.id, 
        liked_feed_item.postable), id: "tpost_link_#{liked_feed_item.id}"
    - if liked_feed_item.postable_type == "Project"
      = link_to liked_feed_item.postable.title,
        user_project_path(liked_feed_item.user.id, 
        liked_feed_item.postable), id: "project_link_#{liked_feed_item.id}"
    - if liked_feed_item.postable_type == "Topic"   
      = link_to liked_feed_item.postable.title, 
        user_topic_path(liked_feed_item.user.id, 
        liked_feed_item.postable), id: "topic_link_#{liked_feed_item.id}"  
    %span.summary= liked_feed_item.postable.summary
  %div  
    %span.user
      = link_to liked_feed_item.user.name, liked_feed_item.user  
    %span.timestamp
      Posted #{time_ago_in_words(liked_feed_item.created_at)} ago
    - if current_user == liked_feed_item.user
      = link_to "delete", liked_feed_item, method: :delete, |
        data: { confirm: "You sure?" },                       |
        title: liked_feed_item.postable.title                        |
    %span.post_info
    - if liked_feed_item.likes_count > 0
      %strong#liking.stat #{liked_feed_item.likes_count}
      favorites

app/views/shared/_likers_list.html.haml
.user_avatars
  - if @likers.any?
    - @likers.each do |liker|
      = link_to avatar_for(liker, size: 30), liker, id: 'liker_id_' + liker.id.to_s

app/views/shared/_project_publicise_form.html.haml
= form_tag({:controller => "projects",:action => "publicise"}, {:method => "put"}) do
  = submit_tag "Publicise", class: "btn btn-large btn-primary"
  %table
    %tbody
      %tr
        %td
          %span
            = image_tag 'linkedin-icon.png', class: "publicise_icon"      
          %span
            = check_box_tag(:linkedin_pub, '1', false, {:disabled => !@linkedin_auth })    
        %td
          %span
            = image_tag 'Twitter-Blue-Transparent-t-3D-Button-Logo.png', class: "publicise_icon"     
          %span
            = check_box_tag(:twitter_pub, '1', false, {:disabled => !@twitter_auth }) 
        %td
          %span.hide
            = image_tag 'facebook_icon.png', class: "publicise_icon"      
          %span.hide
            = check_box_tag(:facebook_pub, '1', false, {:disabled => true }) 
  %span
    = link_to "add networks", authentications_path if !@twitter_auth || !@linkedin_auth                                                       
  
  
 
       

app/views/shared/_tags.html.haml
%ol.tag
  = render partial: 'shared/tags_item', collection: @tags_item

app/views/shared/_tags_filter_item.html.haml
%li
  %span.label= tags_filter_item.name

app/views/shared/_tags_item.html.haml
%li
  = link_to tags_item.name, post_path(tags_item.name), :class => 'label'

app/views/shared/_topic_feed.html.haml
%ol.feed
  = render partial: 'shared/topic_feed_item', collection: @topic_feed_items
= will_paginate @topic_feed_items, :param_name => 'topic_page', 
                previous_label: h("<"), next_label: h(">"), 
                inner_window: 2, outer_window: 2

app/views/shared/_topic_feed_item.html.haml
%li.feedpost{:id => topic_feed_item.id}
  -if topic_feed_item.postable_type == "Project"
    -if topic_feed_item.postable.projectdraftimages.count == 0
      = avatar_for topic_feed_item.user, size: 52 
    -else
      = image_tag(topic_feed_item.postable.projectdraftimages.first.image_url(:thumb).to_s, alt: "", class: "img-polaroid")    
  -if topic_feed_item.postable_type == "Topic"
    -if topic_feed_item.postable.topicdraftimages.count == 0
      = avatar_for topic_feed_item.user, size: 52 
    -else
      = image_tag(topic_feed_item.postable.topicdraftimages.first.image_url(:thumb).to_s, alt: "", class: "img-polaroid")    
  %div
    = link_to topic_feed_item.postable.title, user_topic_path(topic_feed_item.user.id, topic_feed_item.postable), id: "topic_link_#{topic_feed_item.id}"
    %span.summary= topic_feed_item.postable.summary
  %div
    %span.user
      = link_to topic_feed_item.user.name, topic_feed_item.user  
    %span.timestamp
      Posted #{time_ago_in_words(topic_feed_item.created_at)} ago.
    - if current_user == topic_feed_item.user
      = link_to "delete", topic_feed_item, method: :delete, |
        data: { confirm: "You sure?" },                       |
        title: topic_feed_item.postable.title                        |
    %span.post_info
    - if topic_feed_item.likes_count > 0
      %strong#liking.stat #{topic_feed_item.likes_count}
      favorites

app/views/shared/_topic_form.html.haml
= form_for(topic, :url => user_topics_url(@post.user.id)) do |f|
  = render partial: 'shared/error_messages', locals: {object: f.object}
  .field
    %h2.span8 New Topic
    %p.span8
      .span1
        = f.label :title, "Title"
      .span6  
        = f.text_field :title, placeholder: "Topic title..."
    %p.span8
      .span1
        = f.label :summary, "Summary"
      .span6          
        = f.text_area :summary, placeholder: "Topic summary...", rows: 3
    %p.span8
      .span1
        = f.label :reference, "Links & references"
      .span6   
        = f.text_area :reference, :id =>'reference_textarea', placeholder: "Topic references and links..."                     
    %p.span8
      .span1
        = f.label :tag_list, "Tags"
      .span6       
        = f.text_field :tag_list, placeholder: "Comma separated tags..."      
    %p.span8   
      = f.text_area :content, :id =>'content_textarea', placeholder: "Topic content..."
    %p.span8  
      = f.submit "Submit topic", class: "btn btn-large btn-primary"  

app/views/shared/_topic_publicise_form.html.haml
= form_tag({:controller => "topics",:action => "publicise"}, {:method => "put"}) do
  = submit_tag "Publicise", class: "btn btn-large btn-primary"
  %table
    %tbody
      %tr
        %td
          %span
            = image_tag 'linkedin-icon.png', class: "publicise_icon"      
          %span
            = check_box_tag(:linkedin_pub, '1', false, {:disabled => !@linkedin_auth })    
        %td
          %span
            = image_tag 'Twitter-Blue-Transparent-t-3D-Button-Logo.png', class: "publicise_icon"     
          %span
            = check_box_tag(:twitter_pub, '1', false, {:disabled => !@twitter_auth }) 
        %td
          %span.hide
            = image_tag 'facebook_icon.png', class: "publicise_icon"      
          %span.hide
            = check_box_tag(:facebook_pub, '1', false, {:disabled => true }) 
  %span
    = link_to "add networks", authentications_path if !@twitter_auth || !@linkedin_auth                                                       
  
  
 
       

app/views/shared/_tpost_form.html.haml
= form_for(tpost, :url => user_tposts_url(@post.user.id)) do |f|
  = render partial: 'shared/error_messages', locals: {object: f.object}
  .field
    = f.text_area :title, placeholder: "Topic title..."
    = f.text_area :summary, placeholder: "Topic summary..."
  = f.submit "Submit topic", class: "btn btn-large btn-primary"

app/views/shared/_user_feed_item.html.haml
%li
  = avatar_for user, size: 52
  = link_to user.name, user